Repository chayanika840/Project, pull requests merged in 2022-10, with the labels that each got.

#4 gfg solutions
  Circular tour.cpp
  First negative integer in every window of size k.cpp
  First non-repeating character in a stream.cpp
Labels: enhancement, hacktoberfest

#5 Create reversestring.cpp
  reversestring.cpp
Labels: good first issue, cpp, hacktoberfest

#6 queue and heap related
  Is Binary Tree Heap.cpp
  Queue Reversal.cpp
  Reverse First K elements of Queue.cpp
Labels: hacktoberfest

#7 update in readme
  README.md
Labels: hacktoberfest

#10 Update README.md
  README.md
Labels: documentation, hacktoberfest

#9 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest

#8 Create reverse array gfg solution
  reverse array gfg solution
Labels: cpp, hacktoberfest

#15 Create RotateRight.java
  Java/RotateRight.java
Labels: hacktoberfest, java

#14 Create Frequency.java
  Java/Frequency.java
Labels: hacktoberfest, java

#13 Create ReverseArray.java
  Java/ReverseArray.java
Labels: hacktoberfest, java

#12 Create Contributers
  Contributers
Labels: documentation, hacktoberfest

#16 Added some starter problems of java
  Java/abcSubsequence.java
  Java/allIdxRec.java
  Java/anyBaseAdd.java
  Java/anyBaseDiv.java
  Java/anyBaseProd.java
  Java/anyBaseSub.java
  Java/anyToAny.java
Labels: hacktoberfest

#17 Added some DSA practice questions in Java
  Java/1. Find the duplicate num.java
  Java/10. Best Time Stock Buy Sell.java
  Java/11. Next Permutation.java
  Java/12. Count_Inversions.java
  Java/13. Pow x,n.java
  Java/14. Majority Element.java
  Java/15. Majority Element II.java
  Java/16. Unique Paths.java
  Java/17. Reverse Pairs.java
  Java/2. Sort 0's, 1's, 2's or sort colors.java
  Java/3. Maximum Subarray Sum or Kadane's algo.java
  Java/4. Merge Intervals.java
  Java/5. Rotate Matrix.java
  Java/6. Search in a 2D Matrix.java
  Java/7. Search in a 2D Matrix - II.java
  Java/8. Set Matrix Zeros.java
  Java/9. Pascal Triangle.java
Labels: hacktoberfest

#18 Update Circular tour.cpp
  Circular tour.cpp
  Is Binary Tree Heap.cpp
Labels: hacktoberfest

#19 Update reversestring.cpp
  reversestring.cpp
Labels: hacktoberfest

#23 Update README.md
  README.md
Labels: documentation, hacktoberfest

#22 Update README.md
  README.md
Labels: documentation, hacktoberfest

#21 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest

#25 Update Reverse First K elements of Queue.cpp
  Reverse First K elements of Queue.cpp
Labels: hacktoberfest

#29 stack implementation
  stack implementation
Labels: hacktoberfest

#28 pascal triangle
  pascal triangle
Labels: hacktoberfest

#27 date time
  date time
Labels: hacktoberfest

#26 joshstring
  joshstring
Labels: hacktoberfest

#30 FizzBuzz
  FizzBuzz
Labels: hacktoberfest

#34 Create Insertion Sort
  Insertion Sort
Labels: hacktoberfest

#33 Create Substring
  Substring
Labels: hacktoberfest

#32 Create Kadane's Algorithm
  Kadane's Algorithm
Labels: hacktoberfest

#31 Create Bubble sort
  Bubble sort
Labels: hacktoberfest

#38 Rain Water Problem O(n)
  Rain Water Problem O(n)
Labels: hacktoberfest

#37 Count Letters numbers space and others
  Count Letters numbers space and others
Labels: hacktoberfest

#36 Create TOH using recursion
  TOH using recursion
Labels: hacktoberfest

#40 Added Patterns.java into Java directory
  Java/.idea/.gitignore
  Java/.idea/misc.xml
  Java/.idea/modules.xml
  Java/.idea/runConfigurations.xml
  Java/.idea/vcs.xml
  Java/Patterns.java
  Java/Project.iml
  Java/out/production/Project/.idea/.gitignore
  Java/out/production/Project/.idea/misc.xml
  Java/out/production/Project/.idea/modules.xml
  Java/out/production/Project/.idea/runConfigurations.xml
  Java/out/production/Project/.idea/vcs.xml
  Java/out/production/Project/Project.iml
Labels: hacktoberfest
